services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: foo
    networks:
      barbnet:
  server:
    build: ./barbara_server
    depends_on:
      - db
    networks:
      barbnet:
      hostnet:
networks:
  barbnet:
  hostnet:
    external: True
    name: host